### ISSUE TITLE
Web Scraping from Dev.to Articles 

### ISSUE THREAD

**Issue by kpolnitz** [AnshG714/sweeger#4]
In addition to scraping from Medium articles, we should have the ability to scrape from Dev.to articles. Using multiple websites allows for a wider range of information for the fellows to use.

**Comment by AnshG714** [comment]
Yee, check out [this markdown file](https://github.com/AnshG714/sweeger/blob/master/scraper/links.md) on master

**Comment by kpolnitz** [comment]
@AnshG714 it might be a good place to list all of the links we end up using for the parser!
